[General]
network = IntersectionScenarioInet
sim-time-limit = 300s
debug-on-errors = true
cmdenv-express-mode = true

# Veins-INET manager
*.manager.updateInterval = 0.1s
*.manager.host = "localhost"
*.manager.port = 9999
*.manager.autoShutdown = true
*.manager.launchConfig = xmldoc("intersection.launchd.xml")
*.manager.moduleType = "benchmark.veins_inet.VeinsInetCar"
*.manager.moduleName = "node"
*.manager.moduleDisplayString = ""

# Node mobility
*.node[*].mobility.typename = "VeinsInetMobility"

# RAFT Application
*.node[*].numApps = 1
*.node[*].app[0].typename = "WillemtRaftApplication"
*.node[*].app[0].middleware.typename = "benchmark.raft.WillemtRaftApplication"
*.node[*].app[0].totalVehicles = 32
*.node[*].app[0].approachEdges = "-34894202#13,34894202#10,36905242#11,37551802#8"
*.node[*].app[0].exitEdges = "-34894202#10,34894202#13,-37551802#8,-36905242#11"
*.node[*].app[0].resultsFile = "raft_results.json"

# RAFT Timing
*.node[*].app[0].electionTimeoutBaseMs = 500
*.node[*].app[0].electionTimeoutJitterMs = 1000
*.node[*].app[0].requestTimeoutMs = 200
*.node[*].app[0].maxFailedElections = 100
*.node[*].app[0].fallbackWaitMinMs = 100
*.node[*].app[0].fallbackWaitMaxMs = 300
*.node[*].app[0].passConfirmationMs = 300
*.node[*].app[0].statusCollectionTimeoutMs = 200

# Wi-Fi
*.node[*].wlan[0].typename = "Ieee80211Interface"
*.node[*].wlan[0].radio.typename = "Ieee80211ScalarRadio"
*.node[*].wlan[0].radio.transmitter.communicationRange = 500m
*.node[*].wlan[0].radio.transmitter.power = 20mW
*.node[*].wlan[0].mac.dcf.channelAccess.cwMin = 7
*.node[*].wlan[0].radio.receiver.sensitivity = -85dBm
*.node[*].wlan[0].radio.centerFrequency = 5.9GHz
*.node[*].wlan[0].radio.bandwidth = 10MHz
